[docker_context]
symbol = "ğŸ‹ "
disabled = true

[elixir]
symbol = "ğŸ”® "
disabled = true

[nodejs]
disabled = true

[aws]
disabled = true

[kubernetes]
format = 'on [â›µ $context](dimmed green) '
disabled = false

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
"arn:aws:eks:us-east-1:583851570477:cluster/realm-staging" = "staging"
"arn:aws:eks:us-east-1:583851570477:cluster/realm-production-v5" = "production"

[package]
disabled = true

[gcloud]
disabled = true
